### ISSUE TITLE
Add validate method

### ISSUE THREAD

**Issue by SimonG96** [SimonG96/LightweightIocContainer#44]
Add a `Validate()` method to the `IIocContainer` that can be called from a test and checks if all registered types in the given installers can be resolved.

**Comment by theKBro** [comment]
How to validate factories?
```
ValidateFactories().WithArgument<IABC>(new ABC()).WithArgument<IBCE>(new BCE());
```
or more specific?

**Comment by SimonG96** [comment]
Not quite sure yet

**Comment by theKBro** [comment]
better:
```
container.AddFactoryValidation<ITestFactory>().WithArgument<string>("hi");
..
..
container.ValidateFactories()
```
throwing exception if not for all factories a validation is registered

**Comment by theKBro** [comment]
What about factories with multiple create methods?

**Comment by SimonG96** [comment]
Validate everything by calling `Validate()`
Special parameters can be added by calling `AddParameter<TInterface, TParameter>(parameter)`

**Comment by SimonG96** [comment]
> What about factories with multiple create methods?

Every create method is verified if it can successfully create it's type.

**Comment by theKBro** [comment]
Else only one exception is thrown for the first not working resolve? Could you instead throw an Aggregate exception for all not working registrations?

**Comment by SimonG96** [comment]
> Else only one exception is thrown for the first not working resolve? Could you instead throw an Aggregate exception for all not working registrations?

Done 🚀
