### ISSUE TITLE
Resolve implementation that is registered with interface

### ISSUE THREAD

**Issue by SimonG96** [SimonG96/LightweightIocContainer#49]
Allow resolving of an implementation that is registered with an interface.

Registration:

```c#
container.Register<TInterface, TImplementation>();
```

Resolve:

```c#
TImplementation impl = container.Resolve<TImplementation>();
```

**Comment by theKBro** [comment]
Should this also work for dependency injected objects?

**Comment by SimonG96** [comment]
@theKBro: Yes, injected objects are resolved as well:

https://github.com/SimonG96/LightweightIocContainer/blob/34cdbc52df284aacc115b531bc9eb2966364a530/LightweightIocContainer/IocContainer.cs#L559-L560
